name: Production Build & Verify

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Update browserslist database
        run: npx update-browserslist-db@latest
        
      - name: Build for production
        run: npm run build:prod
        
      - name: Verify build output
        run: |
          echo "=== Build Verification ==="
          ls -lh dist/
          echo "CSS file size: $(ls -lh dist/styles.css | awk '{print $5}')"
          
      - name: Check HTML files
        run: |
          echo "=== HTML Files Check ==="
          ls -1 *.html | wc -l
          echo "HTML files found:"
          ls -1 *.html
          
      - name: Test deployment script
        run: npm run deploy:test
        
      - name: Verify deployment configs
        run: |
          echo "=== Deployment Configs ==="
          ls -la netlify.toml vercel.json DEPLOYMENT.md .github/workflows/deploy.yml
          
      - name: Performance check
        run: |
          echo "=== Performance Metrics ==="
          echo "Total HTML size: $(du -sh *.html | awk '{sum+=$1} END {print sum "KB"}')"
          echo "CSS bundle size: $(ls -lh dist/styles.css | awk '{print $5}')"
          
      - name: Success
        run: echo "✅ All checks passed! Production build is ready for deployment." 